# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{orange-flickr}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Haslem"]
  s.date = %q{2010-08-31}
  s.description = %q{Adds flickr functionality to Orange}
  s.email = %q{therabidbanana@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/orange-flickr.rb",
     "lib/orange-flickr/assets/js/yoxview/data/flickr.js",
     "lib/orange-flickr/assets/js/yoxview/data/flickr.min.js",
     "lib/orange-flickr/assets/js/yoxview/data/picasa.js",
     "lib/orange-flickr/assets/js/yoxview/data/picasa.source.js",
     "lib/orange-flickr/assets/js/yoxview/images/empty.gif",
     "lib/orange-flickr/assets/js/yoxview/images/help_panel.png",
     "lib/orange-flickr/assets/js/yoxview/images/left.png",
     "lib/orange-flickr/assets/js/yoxview/images/left_empty.png",
     "lib/orange-flickr/assets/js/yoxview/images/left_eng.png",
     "lib/orange-flickr/assets/js/yoxview/images/left_prev.png",
     "lib/orange-flickr/assets/js/yoxview/images/popup_ajax_loader.gif",
     "lib/orange-flickr/assets/js/yoxview/images/right.png",
     "lib/orange-flickr/assets/js/yoxview/images/right_empty.png",
     "lib/orange-flickr/assets/js/yoxview/images/right_eng.png",
     "lib/orange-flickr/assets/js/yoxview/images/sprites.png",
     "lib/orange-flickr/assets/js/yoxview/install.htm",
     "lib/orange-flickr/assets/js/yoxview/jquery-1.4.2.min.js",
     "lib/orange-flickr/assets/js/yoxview/jquery.jsonp-1.0.4.min.js",
     "lib/orange-flickr/assets/js/yoxview/jquery.swfobject.1-1-1.min.js",
     "lib/orange-flickr/assets/js/yoxview/jquery.yoxthumbs.js",
     "lib/orange-flickr/assets/js/yoxview/jquery.yoxthumbs.min.js",
     "lib/orange-flickr/assets/js/yoxview/jquery.yoxview-2.05.js",
     "lib/orange-flickr/assets/js/yoxview/jquery.yoxview-2.05.min.js",
     "lib/orange-flickr/assets/js/yoxview/lang/ar.js",
     "lib/orange-flickr/assets/js/yoxview/lang/bg.js",
     "lib/orange-flickr/assets/js/yoxview/lang/ca.js",
     "lib/orange-flickr/assets/js/yoxview/lang/cs.js",
     "lib/orange-flickr/assets/js/yoxview/lang/de.js",
     "lib/orange-flickr/assets/js/yoxview/lang/en.js",
     "lib/orange-flickr/assets/js/yoxview/lang/es.js",
     "lib/orange-flickr/assets/js/yoxview/lang/fr.js",
     "lib/orange-flickr/assets/js/yoxview/lang/gr.js",
     "lib/orange-flickr/assets/js/yoxview/lang/he.js",
     "lib/orange-flickr/assets/js/yoxview/lang/ie.js",
     "lib/orange-flickr/assets/js/yoxview/lang/ir.js",
     "lib/orange-flickr/assets/js/yoxview/lang/it.js",
     "lib/orange-flickr/assets/js/yoxview/lang/ja.js",
     "lib/orange-flickr/assets/js/yoxview/lang/mk.js",
     "lib/orange-flickr/assets/js/yoxview/lang/nl.js",
     "lib/orange-flickr/assets/js/yoxview/lang/pl.js",
     "lib/orange-flickr/assets/js/yoxview/lang/pt-br.js",
     "lib/orange-flickr/assets/js/yoxview/lang/pt.js",
     "lib/orange-flickr/assets/js/yoxview/lang/ro.js",
     "lib/orange-flickr/assets/js/yoxview/lang/ru.js",
     "lib/orange-flickr/assets/js/yoxview/lang/sk.js",
     "lib/orange-flickr/assets/js/yoxview/lang/sl.js",
     "lib/orange-flickr/assets/js/yoxview/lang/sv.js",
     "lib/orange-flickr/assets/js/yoxview/lang/tr.js",
     "lib/orange-flickr/assets/js/yoxview/lang/ua.js",
     "lib/orange-flickr/assets/js/yoxview/lang/zh-cn.js",
     "lib/orange-flickr/assets/js/yoxview/lang/zh-tw.js",
     "lib/orange-flickr/assets/js/yoxview/skins/top_menu/sprites.png",
     "lib/orange-flickr/assets/js/yoxview/skins/top_menu/yoxview.top_menu.css",
     "lib/orange-flickr/assets/js/yoxview/skins/top_menu/yoxview.top_menu.js",
     "lib/orange-flickr/assets/js/yoxview/yox.js",
     "lib/orange-flickr/assets/js/yoxview/yox.min.js",
     "lib/orange-flickr/assets/js/yoxview/yoxview-init.js",
     "lib/orange-flickr/assets/js/yoxview/yoxview-nojquery.js",
     "lib/orange-flickr/assets/js/yoxview/yoxview.css",
     "lib/orange-flickr/plugin.rb",
     "lib/orange-flickr/resources/flickr_resource.rb",
     "lib/orange-flickr/views/flickr/galleries.haml",
     "lib/orange-flickr/views/flickr/gallery.haml",
     "lib/orange-flickr/views/flickr/photoset.haml",
     "lib/orange-flickr/views/flickr/show.haml",
     "orange-flickr.gemspec",
     "spec/orange-flickr_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://orangerb.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A gem that uses FlickRaw to integrate with orange}
  s.test_files = [
    "spec/orange-flickr_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<flickraw-cached>, [">= 0"])
      s.add_runtime_dependency(%q<orange-core>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<flickraw-cached>, [">= 0"])
      s.add_dependency(%q<orange-core>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<flickraw-cached>, [">= 0"])
    s.add_dependency(%q<orange-core>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

